name: Red River Resole
short_description: Climb. Repair. Repeat.
description:  Our mission is to give back to the community and help keep fellow climbers on the rock. Climbing shoes are expensive
url: resole.co

permalink: pretty
relative_permalinks: false
include: [_data]

sass:
  sass_dir: assets/css/

plugins:

exclude:
  - node_modules